### ISSUE TITLE
Incoming photo messages get displayed wrong

### ISSUE THREAD

**Issue by schmizzel** [saroar/RealtTimeIOSChat#1]
Hey,
If you are still working at this project you should take a look at the incoming pictures. The bubbles are always displayed as outgoing, even if they are actually incoming.

**Comment by saroar** [comment]
thanks for share if you like to fixed i will happy to marge it :) or i will check sure when i will get time thanks again

**Comment by Alexleet** [comment]
in file DataSource.swift
replace
`let model = MessageModel(uid: item.uid, senderId: item.senderId, type: item.type, isIncoming: false, date: item.date, status: item.status)`
to
`let model = MessageModel(uid: item.uid, senderId: item.senderId, type: item.type, isIncoming: item.isIncoming, date: item.date, status: item.status)`

**Comment by saroar** [comment]
@Alexleet thanks you mean this line? 
https://github.com/saroar/RealtTimeIOSChat/blob/b32e96a71e343c04b73198ed67e4fa115ec35558/ChattoChatApp/DataSource.swift#L121

**Comment by Alexleet** [comment]
> @Alexleet thanks you mean this line?
> 
> https://github.com/saroar/RealtTimeIOSChat/blob/b32e96a71e343c04b73198ed67e4fa115ec35558/ChattoChatApp/DataSource.swift#L121

exactly
